export type User = {
  _id: string;
  id?: string;
  firstName: string;
  lastName: string;
  email: string;
  countryCode?: string | null;
  phone?: string | null;
  epochlagID?: string;
  isVerified?: boolean;
  isArchived?: boolean;
  friends?: string[];
  friendsDetails?: Array<{
    _id: string;
    firstName: string;
    lastName: string;
    epochlagID?: string;
    profilePicture: string | null;
  }>;
  blockedUsers?: string[];
  allowContactDiscovery?: boolean;
  featureUpdatesNotifications?: boolean;
  warningCount?: number;
  promptHighlights?: unknown[];
  moderationWarnings?: unknown[];
  profilePicture?: string | null;
  backgroundPicture?: string | null;
  bio?: string | null;
  city?: string | null;
  country?: string | null;
  state?: string | null;
  dateOfBirth?: string | null;
  googleId?: string;
  onboardingStage?: number;
  totalStories?: number;
  createdAt?: string;
  updatedAt?: string;
};
